const countries = [
  // Europe
  { region: "europe", name: "albania" },
  { region: "europe", name: "andorra" },
  { region: "europe", name: "austria" },
  { region: "europe", name: "belarus" },
  { region: "europe", name: "belgium" },
  { region: "europe", name: "bosnia and herzegovina", other: "bosnia" },
  { region: "europe", name: "bulgaria" },
  { region: "europe", name: "croatia" },
  { region: "europe", name: "czech republic", other: "czech" },
  { region: "europe", name: "denmark" },
  { region: "europe", name: "estonia" },
  { region: "europe", name: "finland" },
  { region: "europe", name: "france" },
  { region: "europe", name: "germany" },
  { region: "europe", name: "greece" },
  { region: "europe", name: "hungary" },
  { region: "europe", name: "iceland" },
  { region: "europe", name: "ireland" },
  { region: "europe", name: "italy" },
  { region: "europe", name: "kosovo" },
  { region: "europe", name: "latvia" },
  { region: "europe", name: "liechtenstein" },
  { region: "europe", name: "lithuania" },
  { region: "europe", name: "luxembourg" },
  { region: "europe", name: "malta" },
  { region: "europe", name: "moldova" },
  { region: "europe", name: "monaco" },
  { region: "europe", name: "montenegro" },
  { region: "europe", name: "netherlands", other: "holland" },
  { region: "europe", name: "macedonia" },
  { region: "europe", name: "norway" },
  { region: "europe", name: "poland" },
  { region: "europe", name: "portugal" },
  { region: "europe", name: "romania" },
  { region: "europe", name: "russia" },
  { region: "europe", name: "san marino" },
  { region: "europe", name: "serbia" },
  { region: "europe", name: "slovakia" },
  { region: "europe", name: "slovenia" },
  { region: "europe", name: "spain" },
  { region: "europe", name: "sweden" },
  { region: "europe", name: "switzerland" },
  { region: "europe", name: "ukraine" },
  { region: "europe", name: "united kingdom", other: "uk" },
  { region: "europe", name: "vatican city", other: "vatican" },

  // Asia
  { region: "asia", name: "afghanistan" },
  { region: "asia", name: "armenia" },
  { region: "asia", name: "azerbaijan" },
  { region: "asia", name: "bahrain" },
  { region: "asia", name: "bangladesh" },
  { region: "asia", name: "bhutan" },
  { region: "asia", name: "brunei" },
  { region: "asia", name: "burma", other: "myanmar" },
  { region: "asia", name: "cambodia" },
  { region: "asia", name: "china" },
  { region: "asia", name: "cyprus" },
  { region: "asia", name: "east timor" },
  { region: "asia", name: "georgia" },
  { region: "asia", name: "india" },
  { region: "asia", name: "indonesia" },
  { region: "asia", name: "iran" },
  { region: "asia", name: "iraq" },
  { region: "asia", name: "israel" },
  { region: "asia", name: "japan" },
  { region: "asia", name: "jordan" },
  { region: "asia", name: "kazakhstan" },
  { region: "asia", name: "kuwait" },
  { region: "asia", name: "kyrgyzstan" },
  { region: "asia", name: "laos" },
  { region: "asia", name: "lebanon" },
  { region: "asia", name: "malaysia" },
  { region: "asia", name: "maldives" },
  { region: "asia", name: "mongolia" },
  { region: "asia", name: "nepal" },
  { region: "asia", name: "north korea" },
  { region: "asia", name: "oman" },
  { region: "asia", name: "pakistan" },
  { region: "asia", name: "philippines" },
  { region: "asia", name: "qatar" },
  { region: "asia", name: "saudi arabia" },
  { region: "asia", name: "singapore" },
  { region: "asia", name: "south korea" },
  { region: "asia", name: "sri lanka" },
  { region: "asia", name: "syria" },
  { region: "asia", name: "taiwan" },
  { region: "asia", name: "tajikistan" },
  { region: "asia", name: "thailand" },
  { region: "asia", name: "turkey" },
  { region: "asia", name: "turkmenistan" },
  { region: "asia", name: "united arab emirates", other: "uae" },
  { region: "asia", name: "uzbekistan" },
  { region: "asia", name: "vietnam" },
  { region: "asia", name: "yemen" },

  // Africa
  { region: "africa", name: "algeria" },
  { region: "africa", name: "angola" },
  { region: "africa", name: "benin" },
  { region: "africa", name: "botswana" },
  { region: "africa", name: "burkina faso" },
  { region: "africa", name: "burundi" },
  { region: "africa", name: "cameroon" },
  { region: "africa", name: "cape verde" },
  { region: "africa", name: "central african republic" },
  { region: "africa", name: "chad" },
  { region: "africa", name: "comoros" },
  { region: "africa", name: "democratic republic of the congo", other: "dr congo" },
  { region: "africa", name: "djibouti" },
  { region: "africa", name: "egypt" },
  { region: "africa", name: "equatorial guinea" },
  { region: "africa", name: "eritrea" },
  { region: "africa", name: "ethiopia" },
  { region: "africa", name: "gabon" },
  { region: "africa", name: "gambia" },
  { region: "africa", name: "ghana" },
  { region: "africa", name: "guinea" },
  { region: "africa", name: "guinea-bissau", other: "guinea bissau" },
  { region: "africa", name: "ivory coast", other: "cote d'ivoire" },
  { region: "africa", name: "kenya" },
  { region: "africa", name: "lesotho" },
  { region: "africa", name: "liberia" },
  { region: "africa", name: "libya" },
  { region: "africa", name: "madagascar" },
  { region: "africa", name: "malawi" },
  { region: "africa", name: "mali" },
  { region: "africa", name: "mauritania" },
  { region: "africa", name: "mauritius" },
  { region: "africa", name: "morocco" },
  { region: "africa", name: "mozambique" },
  { region: "africa", name: "namibia" },
  { region: "africa", name: "niger" },
  { region: "africa", name: "nigeria" },
  { region: "africa", name: "republic of the congo", other: "congo" },
  { region: "africa", name: "rwanda" },
  { region: "africa", name: "sao tome and principe", other: "sao tome" },
  { region: "africa", name: "senegal" },
  { region: "africa", name: "seychelles" },
  { region: "africa", name: "sierra leone" },
  { region: "africa", name: "somalia" },
  { region: "africa", name: "south africa" },
  { region: "africa", name: "south sudan" },
  { region: "africa", name: "sudan" },
  { region: "africa", name: "swaziland" },
  { region: "africa", name: "tanzania" },
  { region: "africa", name: "togo" },
  { region: "africa", name: "tunisia" },
  { region: "africa", name: "uganda" },
  { region: "africa", name: "zambia" },
  { region: "africa", name: "zimbabwe" },

  // North America
  { region: "north america", name: "antigua and barbuda", other: "antigua" },
  { region: "north america", name: "bahamas" },
  { region: "north america", name: "barbados" },
  { region: "north america", name: "belize" },
  { region: "north america", name: "canada" },
  { region: "north america", name: "costa rica" },
  { region: "north america", name: "cuba" },
  { region: "north america", name: "dominica" },
  { region: "north america", name: "dominican republic" },
  { region: "north america", name: "el salvador" },
  { region: "north america", name: "grenada" },
  { region: "north america", name: "guatemala" },
  { region: "north america", name: "haiti" },
  { region: "north america", name: "honduras" },
  { region: "north america", name: "jamaica" },
  { region: "north america", name: "mexico" },
  { region: "north america", name: "nicaragua" },
  { region: "north america", name: "panama" },
  { region: "north america", name: "saint kitts and nevis", other: "st kitts" },
  { region: "north america", name: "saint lucia", other: "st lucia" },
  { region: "north america", name: "saint vincent and the grenadines", other: "st vincent" },
  { region: "north america", name: "trinidad and tobago", other: "trinidad" },
  { region: "north america", name: "united states", other: "us" },

  // South America
  { region: "south america", name: "argentina" },
  { region: "south america", name: "bolivia" },
  { region: "south america", name: "brazil" },
  { region: "south america", name: "chile" },
  { region: "south america", name: "colombia" },
  { region: "south america", name: "ecuador" },
  { region: "south america", name: "guyana" },
  { region: "south america", name: "paraguay" },
  { region: "south america", name: "peru" },
  { region: "south america", name: "suriname" },
  { region: "south america", name: "uruguay" },
  { region: "south america", name: "venezuela" },

  // Oceania
  { region: "oceania", name: "australia" },
  { region: "oceania", name: "fiji" },
  { region: "oceania", name: "kiribati" },
  { region: "oceania", name: "marshall islands" },
  { region: "oceania", name: "micronesia" },
  { region: "oceania", name: "nauru" },
  { region: "oceania", name: "new zealand" },
  { region: "oceania", name: "palau" },
  { region: "oceania", name: "papua new guinea" },
  { region: "oceania", name: "samoa" },
  { region: "oceania", name: "solomon islands" },
  { region: "oceania", name: "tonga" },
  { region: "oceania", name: "tuvalu" },
  { region: "oceania", name: "vanatu" }
];

export default countries;
